name: amar_tali_app
description: Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  sqflite: ^2.3.0
  path:
  path_provider:
  provider:
  shared_preferences:
  logger:
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  firebase_storage: ^11.5.0
  cloud_firestore:
  flutter_animate: ^4.2.0+1
  pdf: ^3.10.6
  connectivity_plus: ^3.0.2
  open_document: ^1.0.7
  open_file: ^3.3.2
  permission_handler: ^11.0.1           
  device_info_plus: ^9.1.0
  lecle_downloads_path_provider: ^0.0.2+8
  loading_animation_widget: ^1.2.0+4
  simple_circular_progress_bar: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  freezed:

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
